# Generated by Django 6.0.5 on 2026-05-13 09:10

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=100)),
                ('est_lieu_reunion', models.BooleanField(default=False)),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=255)),
                ('nom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=30, null=True)),
                ('adresse', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.adresse')),
            ],
        ),
        migrations.CreateModel(
            name='Adhesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('MO', 'Membre officiel'), ('IP', 'Invité permanent')], default='MO', max_length=2)),
                ('debut', models.DateField(default=datetime.date.today, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.membre')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('membre', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.membre')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Organe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('nom_court', models.CharField(blank=True, max_length=100, null=True)),
                ('duree_mandat', models.PositiveIntegerField(default=0, help_text="Durée par défaut d'un mandat, en nombre de jours")),
                ('membres', models.ManyToManyField(through='core.Adhesion', to='core.membre')),
            ],
        ),
        migrations.AddField(
            model_name='adhesion',
            name='organe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organe'),
        ),
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut', models.DateTimeField()),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('adresse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.adresse')),
                ('organe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organe')),
            ],
        ),
        migrations.CreateModel(
            name='Procuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurations_donnees', to='core.membre')),
                ('mandataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurations_recues', to='core.membre')),
                ('reunion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.reunion')),
            ],
        ),
        migrations.CreateModel(
            name='MembreReunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('MO', 'Membre officiel'), ('I', 'Invité')], default='MO', max_length=2)),
                ('etat', models.CharField(choices=[('I', 'Invité'), ('A', 'Accepté'), ('AB', 'Absent'), ('P', 'Procuration')], default='I', max_length=2)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.membre')),
                ('reunion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.reunion')),
            ],
        ),
        migrations.AddConstraint(
            model_name='adhesion',
            constraint=models.UniqueConstraint(fields=('organe', 'membre'), name='unique_adhesion_organe_membre'),
        ),
        migrations.AddConstraint(
            model_name='procuration',
            constraint=models.UniqueConstraint(fields=('mandant', 'reunion'), name='unique_procuration_mandant_reunion'),
        ),
    ]
