# Generated by Django 6.0.5 on 2026-05-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tagdocument_reunion_membres_modeledocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='procuration',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='procurations/'),
        ),
    ]
