# Generated by Django 6.0.5 on 2026-05-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_procuration_fichier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organe',
            name='duree_mandat',
            field=models.PositiveIntegerField(default=0, help_text="Durée par défaut d'un mandat, en années (0 = pas de date de fin)"),
        ),
    ]
