# Generated by Django 6.0.5 on 2026-05-25 12:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_duree_mandat_en_annees'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentReunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255)),
                ('fichier', models.FileField(upload_to='documents/reunions/')),
                ('public', models.BooleanField(default=False, help_text='Si coché, le document est accessible via un lien sans authentification.')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reunion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.reunion')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['nom'],
            },
        ),
    ]
