# Generated by Django 6.0.5 on 2026-05-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_document_reunion'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeledocument',
            name='disponible_par_mail',
            field=models.BooleanField(default=True, help_text="Si décoché, ce modèle n'apparaîtra pas dans le formulaire d'envoi d'email."),
        ),
    ]
