# Generated by Django 6.0.5 on 2026-05-25 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_disponible_par_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='adresse',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.adresse'),
        ),
    ]
