# Generated by Django 6.0.5 on 2026-05-25 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_membre_adresse'),
    ]

    operations = [
        migrations.AddField(
            model_name='organe',
            name='preposition',
            field=models.CharField(blank=True, default='', help_text='Préposition à utiliser devant le nom dans les documents (ex: "au", "à l\'", "à la").', max_length=20),
        ),
        migrations.AlterField(
            model_name='reunion',
            name='adresse',
            field=models.ForeignKey(limit_choices_to={'est_lieu_reunion': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.adresse'),
        ),
    ]
