# Generated by Django 6.0.5 on 2026-05-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_organe_preposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='organe',
            name='pronom',
            field=models.CharField(blank=True, default='', help_text='Article défini devant le nom (ex: "le", "la", "l\'").', max_length=10),
        ),
    ]
