# Generated by Django 6.0.5 on 2026-05-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_organe_pronom'),
    ]

    operations = [
        migrations.AddField(
            model_name='reunion',
            name='ordre_du_jour',
            field=models.TextField(blank=True, null=True),
        ),
    ]
