# Generated by Django 6.0.5 on 2026-05-25 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_ordre_du_jour'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailEnvoye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envoye_le', models.DateTimeField(auto_now_add=True)),
                ('sujet', models.CharField(max_length=255)),
                ('corps', models.TextField()),
                ('destinataires', models.JSONField()),
                ('reply_to', models.EmailField(blank=True, max_length=254)),
                ('reunion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails_envoyes', to='core.reunion')),
            ],
            options={
                'verbose_name': 'Email envoyé',
                'verbose_name_plural': 'Emails envoyés',
                'ordering': ['-envoye_le'],
            },
        ),
    ]
