# Generated by Django 6.0.5 on 2026-05-27 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_email_envoye'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentreunion',
            name='reunion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.reunion'),
        ),
    ]
