# Generated by Django 6.0.5 on 2026-05-29 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            sql='CREATE SCHEMA IF NOT EXISTS viale_manager',
            reverse_sql='DROP SCHEMA IF EXISTS viale_manager CASCADE',
        ),
        migrations.CreateModel(
            name='AutoMails',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sujet', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('type', models.CharField(max_length=255)),
                ('time_delta', models.IntegerField(blank=True, db_comment="donne le nombre de jour de différence avec l'évènement visé", null=True)),
                ('actif', models.BooleanField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"viale_manager"."auto_mails"',
            },
        ),
        migrations.CreateModel(
            name='Houses',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('community', models.BooleanField()),
                ('displayhousenamewithroom', models.BooleanField(db_column='displayHouseNameWithRoom')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"viale_manager"."houses"',
            },
        ),
        migrations.CreateModel(
            name='MaisonneesPlanning',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('begin', models.DateField()),
                ('end', models.DateField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"viale_manager"."maisonnees_planning"',
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('type', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '"viale_manager"."messages"',
            },
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('is_default', models.BooleanField()),
                ('remarques', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"viale_manager"."profiles"',
            },
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('authorize_edition', models.BooleanField()),
                ('link_token', models.UUIDField(unique=True)),
                ('max_days_change', models.IntegerField()),
                ('max_visitors', models.IntegerField()),
                ('remarques_visiteur', models.TextField(blank=True, null=True)),
                ('remarques_accueil', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('link_sent', models.BooleanField()),
                ('contact_email', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('all_mails_required', models.BooleanField()),
                ('groupe', models.BooleanField(db_comment='Est-ce une réservation pour un groupe, active formulaire simplifié')),
                ('nom_groupe', models.CharField(blank=True, db_comment='Nom du groupe', max_length=255, null=True)),
            ],
            options={
                'db_table': '"viale_manager"."reservations"',
            },
        ),
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('date_de_naissance', models.DateField(blank=True, null=True)),
                ('confirmed', models.BooleanField()),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('remarques', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Visiteur',
                'db_table': '"viale_manager"."visitors"',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='HousesInMaisonneesPlanning',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viale_manager.houses')),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viale_manager.maisonneesplanning')),
            ],
            options={
                'db_table': '"viale_manager"."houses_in_maisonnees_planning"',
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('beds', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='viale_manager.houses')),
            ],
            options={
                'db_table': '"viale_manager"."rooms"',
            },
        ),
        migrations.CreateModel(
            name='Sejours',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('confirmed', models.BooleanField()),
                ('remove_from_stats', models.BooleanField()),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viale_manager.reservations')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='viale_manager.rooms')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viale_manager.visitors')),
            ],
            options={
                'db_table': '"viale_manager"."sejours"',
            },
        ),
        migrations.CreateModel(
            name='AssignationsMaisonnees',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viale_manager.houses')),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viale_manager.maisonneesplanning')),
                ('sejour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viale_manager.sejours')),
            ],
            options={
                'db_table': '"viale_manager"."assignations_maisonnees"',
            },
        ),
    ]
