# Generated by Django 6.0.5 on 2026-09-27 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viale_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automails',
            options={'verbose_name': 'email automatique', 'verbose_name_plural': 'emails automatiques'},
        ),
        migrations.AlterModelOptions(
            name='messages',
            options={'verbose_name': 'message'},
        ),
        migrations.AlterModelOptions(
            name='sejours',
            options={'verbose_name': 'séjour'},
        ),
        migrations.AddField(
            model_name='maisonneesplanning',
            name='houses',
            field=models.ManyToManyField(through='viale_manager.HousesInMaisonneesPlanning', to='viale_manager.houses'),
        ),
        migrations.AlterField(
            model_name='automails',
            name='actif',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='automails',
            name='body',
            field=models.TextField(help_text="Contenu HTML de l'email."),
        ),
        migrations.AlterField(
            model_name='automails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='automails',
            name='time_delta',
            field=models.IntegerField(blank=True, db_comment="donne le nombre de jour de différence avec l'évènement visé", help_text="Nombre de jours d'écart avec l'évènement visé (négatif = avant, positif = après).", null=True, verbose_name='décalage (jours)'),
        ),
        migrations.AlterField(
            model_name='automails',
            name='type',
            field=models.CharField(choices=[('arrival', "Arrivée — relatif à la date d'arrivée (décalage en jours)"), ('confirmation', 'Confirmation — envoyé à la confirmation de la réservation')], max_length=255),
        ),
        migrations.AlterField(
            model_name='automails',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='houses',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='houses',
            name='displayhousenamewithroom',
            field=models.BooleanField(db_column='displayHouseNameWithRoom', default=False),
        ),
        migrations.AlterField(
            model_name='houses',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='maisonneesplanning',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='maisonneesplanning',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='message',
            field=models.TextField(help_text='Contenu HTML affiché dans le formulaire de réservation.'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='type',
            field=models.CharField(choices=[('link', 'Lien — affiché au début du formulaire'), ('confirmation', 'Confirmation — affiché à la fin du formulaire')], max_length=255),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='is_default',
            field=models.BooleanField(verbose_name='par défaut'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='beds',
            field=models.IntegerField(verbose_name='lit'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='viale_manager.houses', verbose_name='maison'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='name',
            field=models.CharField(max_length=255, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='sejours',
            name='arrival_date',
            field=models.DateField(verbose_name="date d'arrivée"),
        ),
        migrations.AlterField(
            model_name='sejours',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='confirmé'),
        ),
        migrations.AlterField(
            model_name='sejours',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='sejours',
            name='departure_date',
            field=models.DateField(blank=True, null=True, verbose_name='date de départ'),
        ),
        migrations.AlterField(
            model_name='sejours',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='prix'),
        ),
        migrations.AlterField(
            model_name='sejours',
            name='remove_from_stats',
            field=models.BooleanField(default=False, verbose_name='retirer des statistiques'),
        ),
        migrations.AlterField(
            model_name='sejours',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viale_manager.reservations', verbose_name='reservation'),
        ),
        migrations.AlterField(
            model_name='sejours',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='sejours',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viale_manager.visitors', verbose_name='Visiteur'),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
