# Generated by Django 6.0.5 on 2026-09-27 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viale_manager', '0002_alignement_modeles'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorContacts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('email', 'Email'), ('phone', 'Téléphone')], max_length=10)),
                ('value', models.CharField(max_length=255, verbose_name='valeur')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='viale_manager.visitors')),
            ],
            options={
                'verbose_name': 'autre coordonnée',
                'verbose_name_plural': 'autres coordonnées',
                'db_table': '"viale_manager"."visitor_contacts"',
                'constraints': [models.UniqueConstraint(fields=('visitor', 'type', 'value'), name='visitor_contact_unique')],
            },
        ),
    ]
