# Generated by Django 6.0.5 on 2026-09-27 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viale_manager', '0003_visitor_contacts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maisonneesplanning',
            options={'verbose_name': 'planning des maisonnées', 'verbose_name_plural': 'plannings des maisonnées'},
        ),
        migrations.AlterField(
            model_name='assignationsmaisonnees',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='viale_manager.houses'),
        ),
    ]
