# Generated by Django 6.0.5 on 2026-09-27 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viale_manager', '0004_maisonnees_a_placer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='visitors',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visiteur', to=settings.AUTH_USER_MODEL, verbose_name='compte'),
        ),
    ]
