# Generated by Django 6.1.1 on 2026-09-27 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viale_manager', '0005_visitor_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservations',
            options={'verbose_name': 'réservation'},
        ),
    ]
