# Generated by Django 6.1.1 on 2026-09-27 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viale_manager', '0006_reservations_verbose_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sejours',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='viale_manager.visitors', verbose_name='Visiteur'),
        ),
    ]
