# Generated by Django 6.1.1 on 2026-09-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viale_manager', '0007_sejour_visitor_protect'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='link_valid_from',
            field=models.DateTimeField(blank=True, help_text='Départ de la validité du lien (création ou dernier envoi) ; à défaut, la création.', null=True),
        ),
    ]
