# Generated by Django 6.1.1 on 2026-09-27 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viale_manager', '0008_reservation_link_valid_from'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sejours',
            options={'permissions': [('view_statistiques', 'Peut voir les statistiques (nuitées et revenus)')], 'verbose_name': 'séjour'},
        ),
    ]
