# Generated by Django 6.1.1 on 2026-09-28 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viale_manager', '0009_permission_statistiques'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sejours',
            options={'permissions': [('view_statistiques', 'Peut voir les statistiques (nuitées et revenus)'), ('change_remove_from_stats', 'Peut exclure un séjour des statistiques')], 'verbose_name': 'séjour'},
        ),
    ]
