"""
Django settings for dj_asbl project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from django.urls import reverse_lazy
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DEBUG=(bool, False),
)

_env_file = Path(BASE_DIR, '.env')
if _env_file.exists():
    environ.Env.read_env(_env_file, overwrite=False)

SECRET_KEY = env.str('SECRET_KEY', default='django-insecure-kx)990r2e2z2(1#7simh8hxu*qec77o2#k2jd(gd6b7byvxj$)')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=True)

ALLOWED_HOSTS = env.list('DJANGO_ALLOWED_HOSTS', default=['*'])
CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[])

# Application definition

UNFOLD = {
    'SITE_TITLE': 'Gestion ASBL la Viale Lozère - Quartier Gallet',
    'SITE_HEADER': 'Gestion ASBL la Viale Lozère - Quartier Gallet',
    'SITE_SYMBOL': 'handshake',
    'SHOW_BACK_BUTTON': True,
    'DASHBOARD_CALLBACK': 'core.checks.dashboard_callback',
    'SIDEBAR': {
        'show_search': True,
        'show_all_applications': True,
        'navigation': [
            {
                'title': 'Réunions',
                'separator': False,
                'items': [
                    {
                        'title': 'Réunions',
                        'icon': 'event',
                        'link': reverse_lazy('admin:core_reunion_changelist'),
                        'permission': lambda request: request.user.has_perm('core.view_reunion'),
                    },
                    {
                        'title': 'Emails envoyés',
                        'icon': 'mail',
                        'link': reverse_lazy('admin:core_emailenvoye_changelist'),
                        'permission': lambda request: request.user.has_perm('core.view_emailenvoye'),
                    },
                ],
            },
            {
                'title': 'Membres',
                'separator': True,
                'items': [
                    {
                        'title': 'Membres',
                        'icon': 'group',
                        'link': reverse_lazy('admin:core_membre_changelist'),
                        'permission': lambda request: request.user.has_perm('core.view_membre'),
                    },
                    {
                        'title': 'Organes',
                        'icon': 'corporate_fare',
                        'link': reverse_lazy('admin:core_organe_changelist'),
                        'permission': lambda request: request.user.has_perm('core.view_organe'),
                    },
                ],
            },
            {
                'title': 'Documents',
                'separator': True,
                'items': [
                    {
                        'title': 'Documents',
                        'icon': 'folder',
                        'link': reverse_lazy('admin:core_documentreunion_changelist'),
                        'permission': lambda request: request.user.has_perm('core.view_documentreunion'),
                    },
                    {
                        'title': 'Modèles de documents',
                        'icon': 'description',
                        'link': reverse_lazy('admin:core_modeledocument_changelist'),
                        'permission': lambda request: request.user.has_perm('core.view_modeledocument'),
                    },
                    {
                        'title': 'Tags',
                        'icon': 'label',
                        'link': reverse_lazy('admin:core_tagdocument_changelist'),
                        'permission': lambda request: request.user.has_perm('core.view_tagdocument'),
                    },
                ],
            },
            {
                'title': 'Administration',
                'separator': True,
                'items': [
                    {
                        'title': 'Utilisateurs',
                        'icon': 'manage_accounts',
                        'link': reverse_lazy('admin:core_user_changelist'),
                        'permission': lambda request: request.user.has_perm('core.view_user'),
                    },
                    {
                        'title': 'Groupes',
                        'icon': 'groups',
                        'link': reverse_lazy('admin:auth_group_changelist'),
                        'permission': lambda request: request.user.has_perm('auth.view_group'),
                    },
                    {
                        'title': 'Adresses',
                        'icon': 'location_on',
                        'link': reverse_lazy('admin:core_adresse_changelist'),
                        'permission': lambda request: request.user.has_perm('core.view_adresse'),
                    },
                    {
                        'title': 'Configuration',
                        'icon': 'tune',
                        'link': reverse_lazy('admin:constance_config_changelist'),
                        'permission': lambda request: request.user.has_perm('constance.change_config'),
                    },
                ],
            },
        ],
    },
}

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.constance',
    'unfold.contrib.forms',
    'unfold.contrib.import_export',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'constance',
    'import_export',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dj_asbl.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

AUTH_USER_MODEL = 'core.User'

WSGI_APPLICATION = 'dj_asbl.wsgi.application'


# Database

def _pg(**kwargs):
    return {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env.str('POSTGRES_DB', default='dj_asbl'),
        'USER': env.str('POSTGRES_USER', default='postgres'),
        'PASSWORD': env.str('POSTGRES_PASSWORD', default=''),
        'HOST': env.str('POSTGRES_HOST', default='localhost'),
        'PORT': env.str('POSTGRES_PORT', default='5432'),
        **kwargs,
    }

DATABASES = {
    'default': _pg(),
    'viale': _pg(OPTIONS={'options': '-c search_path=viale_manager'}),
}

DATABASE_ROUTERS = ['dj_asbl.router.DBRouter']


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Constance

CONSTANCE_BACKEND = 'constance.backends.database.DatabaseBackend'

CONSTANCE_ADDITIONAL_FIELDS = {
    'membre_select': ['core.forms.MembreChoiceField', {}],
}

CONSTANCE_CONFIG = {
    'REPLY_TO_EMAIL': ('', "Adresse email de réponse par défaut (reply-to) pour les envois depuis l'admin."),
    'SECRETAIRE_ID': (0, "Membre secrétaire de l'ASBL (disponible dans les modèles de documents)", 'membre_select'),
    'PRESIDENT_ID': (0, "Membre président de l'ASBL (disponible dans les modèles de documents)", 'membre_select'),
}

# Email

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = env.str('SMTP_HOST', default='localhost')
EMAIL_PORT = env.int('SMTP_PORT', default=25)
EMAIL_USE_TLS = env.bool('SMTP_USE_TLS', default=False)
EMAIL_USE_SSL = env.bool('SMTP_USE_SSL', default=False)
EMAIL_HOST_USER = env.str('SMTP_USER', default='')
EMAIL_HOST_PASSWORD = env.str('SMTP_PASSWORD', default='')
DEFAULT_FROM_EMAIL = env.str('DEFAULT_FROM_EMAIL', default='asbl@localhost')

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Europe/Brussels'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage'},
}

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'
